/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.gf.SmartUnitTest.service.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.gf.SmartUnitTest.service.impl.CalculatorServiceImpl;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CalculatorServiceImpl_SSTest extends CalculatorServiceImpl_SSTest_scaffolding {
// allCoveredLines:[7, 10, 15, 20, 25, 26, 27, 30]

  @Test(timeout = 4000)
  public void test_add_0()  throws Throwable  {
      //caseID:7a1a7691622f7ee72b8c434e5f97b27f
      //CoveredLines: [7, 10]
      //Input_0_int: 1
      //Input_1_int: 0
      //Assert: assertEquals(1, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: add
      int int0 = calculatorServiceImpl0.add(1, 0);
      
      //Test Result Assert
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test_divide_1()  throws Throwable  {
      //caseID:25eb6491ee42890e15f1d635473ef005
      //CoveredLines: [7, 25, 30]
      //Input_0_int: 
      //Input_1_int: 
      //Assert: assertEquals(1, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: divide
      int int0 = calculatorServiceImpl0.divide((-1), (-1));
      
      //Test Result Assert
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test_divide_2()  throws Throwable  {
      //caseID:13ded772326c743a85a8ed23172e72b7
      //CoveredLines: [7, 25, 26, 27]
      //Input_0_int: 0
      //Input_1_int: 0
      //Assert: assertEquals((-1), method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: divide
      int int0 = calculatorServiceImpl0.divide(0, 0);
      
      //Test Result Assert
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test_minus_3()  throws Throwable  {
      //caseID:ebcb7db3518b736a4920554715e85b16
      //CoveredLines: [7, 15]
      //Input_0_int: 1
      //Input_1_int: 0
      //Assert: assertEquals(1, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: minus
      int int0 = calculatorServiceImpl0.minus(1, 0);
      
      //Test Result Assert
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test_multiply_4()  throws Throwable  {
      //caseID:27f8e963e70dafbf632883c4d04ebcdc
      //CoveredLines: [7, 20]
      //Input_0_int: 
      //Input_1_int: 
      //Assert: assertEquals(1, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: multiply
      int int0 = calculatorServiceImpl0.multiply((-1), (-1));
      
      //Test Result Assert
      assertEquals(1, int0);
  }
}
