/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.gf.SmartUnitTest;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.gf.SmartUnitTest.SmartUnitTestApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SmartUnitTestApplication_SSTest extends SmartUnitTestApplication_SSTest_scaffolding {
// allCoveredLines:[7, 10]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:b182d474a15260e72fba64b58229bb11
      //CoveredLines: [7, 10]
      //Input_0_String[]: stringArray0
      
      SmartUnitTestApplication smartUnitTestApplication0 = new SmartUnitTestApplication();
      String[] stringArray0 = new String[0];
      
      //Call method: main
      // Undeclared exception!
      try { 
        SmartUnitTestApplication.main(stringArray0);
      } catch(Throwable e) {
         verifyException("org.springframework.core.io.support.SpringFactoriesLoader", e);
         assertEquals("org.smartunit.runtime.mock.java.lang.MockIllegalArgumentException", e.getClass().getName());
         assertEquals("Unable to instantiate factory class [org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.Factory] for factory type [org.springframework.boot.logging.LoggingSystemFactory]", e.getMessage());
      }
  }
}
